### ISSUE TITLE
Showcase

### ISSUE THREAD

**Issue by JnnisCanis** [pretix/pretix-cliques#2]
Is there a public showcase for getting a feeling which usecases this plugin could fit?
I looked at the language files and it sounds like there is some way of user registration? Or do you work with one ticket per user which can be used for multiple events to check-in and -out and the tickets are linked together to one clique?

**Comment by raphaelm** [comment]
No, sorry. This plugin is custom work for a client, we don't advertise or support it officially.

The basic idea is that you and your friends can declare that you belong to the same group during registration. In the client's case, tickets are given out through a lottery and groups either win or lose as a whole.

**Comment by JnnisCanis** [comment]
Thanks. Just one last question: What is the registration? The checkout for buying a ticket?

**Comment by raphaelm** [comment]
Yeah.
